# Generated by Django 2.2.16 on 2022-11-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221105_1728'),
        ('reviews', '0002_auto_20221105_0234'),
    ]

    operations = [
    ]
