# Generated by Django 2.2.16 on 2022-11-05 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221105_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Год выпуска должен быть нашей эры :)'), django.core.validators.MaxValueValidator(2022, message='Год выпуска должен быть не больше текущего')], verbose_name='Год выпуска'),
        ),
    ]
